cloud.aws.credentials:
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}

dynamodb:
  tableName: ${AWS_DYNAMODB_TABLE_NAME}

api:
  stripe:
    key: ${STRIPE_KEY}

cors:
  originPatterns: ${CORS_ORIGINS}

spring:
  security:
    filter:
      dispatcher-types:
        - request
        - error

go.backend.url: ${GO_BACKEND_URL}